"""Users and Doctors Table added

Revision ID: e0bcff345eb2
Revises: 
Create Date: 2022-10-06 00:48:45.579438

"""
from alembic import op
import sqlalchemy as sa
import database

# revision identifiers, used by Alembic.
revision = 'e0bcff345eb2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), autoincrement = True, nullable = False),
                    sa.Column('name', sa.String(length = 50), nullable = True),
                    sa.Column('email', sa.String(length = 100), nullable = True),
                    sa.Column('email_verified', sa.Boolean(), nullable = True),
                    sa.Column('password', database.models.user.Password(), nullable = True),
                    sa.Column('mobile_number', sa.String(length = 11), nullable = False),
                    sa.Column('mobile_verified', sa.Boolean(), nullable = True),
                    sa.Column('profile_image', sa.Text(), nullable = True),
                    sa.Column('user_type', sa.String(), nullable = True),
                    sa.Column('created_at', sa.DateTime(), nullable = True),
                    sa.Column('updated_at', sa.DateTime(), nullable = True),
                    sa.Column('deleted_at', sa.DateTime(), nullable = True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    op.create_table('doctors',
                    sa.Column('id', sa.Integer(), nullable = False),
                    sa.Column('mci_registration_number', sa.Integer(), nullable = True),
                    sa.Column('smc_id', sa.Integer(), nullable = True),
                    sa.Column('specialization', sa.String(length = 20), nullable = True),
                    sa.Column('experience_years', sa.Integer(), nullable = True),
                    sa.Column('user_id', sa.Integer(), nullable = False),
                    sa.Column('created_at', sa.DateTime(), nullable = True),
                    sa.Column('updated_at', sa.DateTime(), nullable = True),
                    sa.Column('deleted_at', sa.DateTime(), nullable = True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_doctors_user_id'), 'doctors', ['user_id'], unique = False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_doctors_user_id'), table_name = 'doctors')
    op.drop_table('doctors')
    op.drop_table('users')
    # ### end Alembic commands ###
